version: '2'

services:

  dms:
    image: andrglo/everest:8.8.1
    hostname: orion
    command: tail -f /dev/null
    working_dir: /andrglo/auth-db
    volumes:
      - ./docker_fish_history:/root/.config/fish/fish_history
      - .:/andrglo/auth-db
    environment:
      - NODE_ENV=development
    restart: always

  redis:
    image: redis:4-alpine
    ports:
      - "6374:6379"
    restart: always





