version: '2'

services:

  dms:
    image: andrglo/everest:15.12.0
    hostname: orion
    command: tail -f /dev/null
    working_dir: /root/auth-db
    volumes:
      - ./docker_fish_history:/root/.config/fish/fish_history
      - .:/root/auth-db
    environment:
      - NODE_ENV=test
      - REDIS_HOST=redis
    restart: always

  redis:
    image: redis:6-alpine
    # ports:
    #   - "6374:6379"
    restart: always





